### ISSUE TITLE
Make sure we can both run with example data 

### ISSUE THREAD

**Issue by cemachelen** [cemac/forest-barc#1]
New version of forest  to play with.

* follow developer guide and run from this clone
* [test data is in the tutorial](https://github.com/cemac/forest-barc/tree/master/forest/tutorial)

**Comment by wolfiex** [comment]
Following a pull from the original repository  ([commit](https://github.com/cemac/forest-barc/commit/8202b77da97bc037aa2443d2625539a5b828a012))  , this works well on mac.

**Comment by wolfiex** [comment]
NOTE a breaking commit on the tutorial file means that there are some changes which stop forest from running. This explained in #343.

The last working commit (and merge) is in
a14dfe8 and can be checked out in the meantime whilst this is resolved on master.

**Comment by wolfiex** [comment]
Commits work in the main forest branch, but not forest-barc. @cemachelen  any idea what the difference between the two that prevents this might be?
